-- Dating apps, track 5: Where it is breaking.
--
-- The routing track, and the last one in the topic. It exists because almost
-- nobody knows which join in their own funnel is failing, so almost everybody
-- optimises the profile — the only part you can edit from the sofa — for
-- months at a time.
--
-- Its last lesson sends a reader whose dates never become second dates to a
-- different topic entirely. That is the only place in this curriculum where a
-- topic diagnoses somebody out of itself, and it is the honest thing to do.

insert into public.lessons (
  skill_id, sort_order, title, theory_md,
  examples_json, checks_json, rubric_json, scenario_json, mission_text
)
values
(
  (select id from public.skills where slug = 'where-it-is-breaking'),
  1,
  'Count before you conclude',
  $md$Four months of effort, no idea what is wrong, and a profile that has been rewritten six times. This is the standard state, and it is caused by one thing: nobody is measuring.

**The move:** write down four weeks of actual numbers before changing anything.

Swipes, matches, conversations that got past two exchanges, dates arranged, dates that happened. Five numbers, kept on a note in your phone, taking about ten seconds a week.

It sounds joyless and it is the opposite, because the alternative is worse. Without numbers you are working from a feeling, and the feeling is generated mostly by the last thing that happened — one good week reads as *this is working now* and one silence reads as *I need new photos*. Neither is true and both produce action.

What the numbers do is locate the break. There are four joins in this — matched, replied, arranged, met — and each one failing means something completely different and needs a different fix. Guessing which one is broken has roughly a one-in-four chance of being right, and people do not guess randomly: they guess the profile, every time, because it is the part they can work on without talking to anybody.

The specific value for somebody quiet is that measurement replaces rumination. Ten seconds of counting is a much better use of a Sunday evening than an hour of rereading a conversation, and it produces something you can act on rather than a mood.

Four weeks is the minimum that means anything. One week is noise — the numbers here are small enough that a single good match distorts everything, which is exactly why a week that felt terrible is not evidence of a problem and a week that felt great is not evidence of a fix.

If you keep one thing: five numbers, four weeks, then decide. You have been fixing the part you could reach rather than the part that was broken.$md$,
  $j$[
    {
      "situation": "Four months in and the profile has been rewritten six times.",
      "line": "(nobody is measuring)",
      "why": "Without numbers you are working from a feeling, and the feeling is generated by whatever happened last. It reliably points at the profile because that is the part you can reach."
    },
    {
      "situation": "You had a terrible week.",
      "line": "(one week is noise)",
      "why": "The numbers are small enough that a single match distorts everything. A bad week is not evidence of a problem and a good one is not evidence of a fix."
    },
    {
      "situation": "You are about to spend Sunday evening rereading a conversation.",
      "line": "(count instead — ten seconds)",
      "why": "Measurement replaces rumination, and it produces something you can act on rather than a mood."
    }
  ]$j$::jsonb,
  $j$[
    {
      "prompt": "Why does everybody optimise their profile?",
      "options": [
        { "text": "Because it is usually the problem.", "correct": false, "note": "Frequently it is fine. It has roughly a one-in-four chance of being the broken join." },
        { "text": "Because it is the part you can work on without talking to anybody.", "correct": true, "note": "People do not guess randomly. They guess the thing they can edit from the sofa, which is why the same photos get changed six times in four months." },
        { "text": "Because it is the first thing anybody sees.", "correct": false, "note": "True, and it explains why it matters rather than why it gets all the attention." },
        { "text": "Because everybody says photos are everything.", "correct": false, "note": "Widely said, and it is repeated because it is actionable rather than because it is always the fault." }
      ],
      "explain": "Four joins, four different fixes. Guessing has a one-in-four hit rate and people do not guess evenly."
    },
    {
      "prompt": "Why four weeks rather than one?",
      "options": [
        { "text": "Because you need a big sample.", "correct": false, "note": "Four weeks is not a big sample either. The reason is narrower than statistics." },
        { "text": "Because behaviour changes when you start measuring.", "correct": false, "note": "It sometimes does, and that is a reason to keep measuring rather than to measure longer first." },
        { "text": "Because the numbers are small enough that one match distorts everything.", "correct": true, "note": "Which is exactly why a week that felt terrible is not evidence of a problem, and a week that felt great is not evidence of a fix." },
        { "text": "Because it takes that long to change anything.", "correct": false, "note": "Some fixes take an afternoon. The waiting is about the reading, not the doing." }
      ],
      "explain": "Five numbers, four weeks, then decide."
    }
  ]$j$::jsonb,
  $j${
    "scale": { "min": 1, "max": 5 },
    "criteria": [
      { "key": "counted", "label": "Actually counted", "description": "Wrote numbers down rather than working from a feeling." },
      { "key": "all_joins", "label": "Counted every join", "description": "Matches, replies, arranged and met — not just matches." },
      { "key": "waited", "label": "Waited four weeks", "description": "Did not act on one week of noise." },
      { "key": "no_guessing", "label": "Did not guess the profile", "description": "Held off rewriting anything until there was a reading." }
    ]
  }$j$::jsonb,
  $j${
    "setting": "A friend has asked how it is going and you have said it is not working and you do not know why.",
    "partner": {
      "name": "Sam",
      "role": "a friend who has used these apps for years",
      "personality": "Asks for numbers at every stage and will not accept impressions. Points out when an answer is a feeling rather than a count.",
      "mood": "Practical.",
      "openness": 5
    },
    "opening_beat": "\"Right — how many matches last month? And how many of those said anything?\"",
    "success_looks_like": "The user recognises they have no numbers and decides to count.",
    "constraints": [
      "Stay in character at all times. Never coach, evaluate or break the scene.",
      "Ask for a number at each stage and note when an impression is offered instead.",
      "Be pleased by a decision to count for a month.",
      "Never suggest what the problem might be."
    ]
  }$j$::jsonb,
  $md$Today, start a note with five numbers in it: swipes, matches, real conversations, dates arranged, dates had. Log this week's.$md$
),
(
  (select id from public.skills where slug = 'where-it-is-breaking'),
  2,
  'No matches',
  $md$If the numbers say almost nobody is matching, this is the one time the answer genuinely is the profile — and specifically two parts of it.

**The move:** change the first photo and the first line, and change nothing else.

The first photo does almost all of the work, because the decision is made in about two seconds and most of them are made on that image alone. If it is a group shot, a distant one, sunglasses, or anything requiring identification, replace it with a clear, recent, solo photograph of your face and change nothing else for two weeks.

The first line is second, and it matters more than the clever prompt at the bottom, which a large proportion of people never scroll to. It has one job — being answerable — and that is track one of this topic in a sentence.

Then change one thing at a time. The universal instinct on a bad month is to rewrite everything, which guarantees you learn nothing: something improves, you have no idea what, and you are back to guessing next month. One change, two weeks, look at the number.

Two things worth ruling out first, because they are boring and they are frequently the whole answer. Check your settings — distance, age range, and whether the app has quietly limited who sees you. And check your volume: some people with a genuine matching problem are swiping twenty times a week, which is not enough attempts for any profile to demonstrate anything.

And if the photos are genuinely fine, the honest possibility is that this is the wrong app for you, or the wrong city, or a very thin local pool. That is not a hidden failing to be discovered by rewriting your bio a seventh time.

If you keep one thing: the first photo, then wait two weeks. One change at a time is the only way to ever know what worked.$md$,
  $j$[
    {
      "situation": "Almost nobody is matching.",
      "line": "(first photo, first line, nothing else)",
      "why": "The decision is made in about two seconds and mostly on the image. The clever prompt at the bottom is not being reached."
    },
    {
      "situation": "You are about to rewrite the whole profile.",
      "line": "(one change, two weeks)",
      "why": "Rewriting everything guarantees you learn nothing — something improves, you have no idea what, and you are guessing again next month."
    },
    {
      "situation": "The photos are genuinely good and it is still flat.",
      "line": "(check the settings and the volume first)",
      "why": "Distance, age range, and twenty swipes a week are boring explanations and they are frequently the whole answer."
    }
  ]$j$::jsonb,
  $j$[
    {
      "prompt": "Which part of the profile actually decides this?",
      "options": [
        { "text": "The prompts at the bottom.", "correct": false, "note": "A large proportion of people never scroll to them. They matter after a match rather than before one." },
        { "text": "The whole thing together.", "correct": false, "note": "The comfortable answer, and it is what produces total rewrites that teach you nothing." },
        { "text": "The first photo, then the first line.", "correct": true, "note": "About two seconds, mostly on the image. Everything else is being decided after that." },
        { "text": "How many photos you have.", "correct": false, "note": "Four good ones beat six of anything, and quantity is not what is failing here." }
      ],
      "explain": "Change one thing and give it two weeks."
    },
    {
      "prompt": "What is worth ruling out before touching anything?",
      "options": [
        { "text": "Your settings and your volume.", "correct": true, "note": "Distance, age range, whether the app has quietly limited your reach — and whether twenty swipes a week is simply too few attempts for any profile to prove anything." },
        { "text": "Whether the app is worth using.", "correct": false, "note": "A question for six months in, not for a flat month with unchecked settings." },
        { "text": "Whether your expectations are realistic.", "correct": false, "note": "That was the previous track. Here you already have numbers saying something is genuinely low." },
        { "text": "Nothing — start with the photos.", "correct": false, "note": "The settings check takes one minute and is frequently the entire answer, which makes it worth doing first." }
      ],
      "explain": "Boring explanations first. They are cheap to check and often the whole thing."
    }
  ]$j$::jsonb,
  $j${
    "scale": { "min": 1, "max": 5 },
    "criteria": [
      { "key": "one_change", "label": "Changed one thing", "description": "Did not rewrite everything at once." },
      { "key": "right_part", "label": "Changed the part that matters", "description": "First photo and first line rather than the bottom of the profile." },
      { "key": "waited", "label": "Gave it two weeks", "description": "Let the change produce a reading." },
      { "key": "ruled_out", "label": "Checked the boring causes", "description": "Settings and volume before content." }
    ]
  }$j$::jsonb,
  $j${
    "setting": "Four weeks of numbers: about six hundred swipes, eleven matches. The conversations that did start went fine.",
    "partner": {
      "name": "Sam",
      "role": "a friend going through the numbers with you",
      "personality": "Reads the funnel from the top and stops at the first join that looks wrong, then asks what specifically will change.",
      "mood": "Focused.",
      "openness": 5
    },
    "opening_beat": "\"Eleven out of six hundred. And the ones that did match went fine, you said?\"",
    "success_looks_like": "The user identifies the top of the funnel and picks one specific change.",
    "constraints": [
      "Stay in character at all times. Never coach, evaluate or break the scene.",
      "Ask what one thing they will change, if the answer is everything.",
      "Ask about settings and swipe volume before content.",
      "Never suggest a specific photo or line."
    ]
  }$j$::jsonb,
  $md$Today, change one thing at the top of your profile and note the date. Log what you changed and when you will look.$md$
),
(
  (select id from public.skills where slug = 'where-it-is-breaking'),
  3,
  'Matches, but nobody talks',
  $md$Matches arrive and nothing happens. This one is easy to misread, because it feels like the same failure as having no matches and it is not — your profile is working. Something later is not.

**The move:** find out whether you are sending them, and what they look like.

Two questions, in order.

**Are you actually sending anything?** A surprising number of people with this exact complaint have a list of matches and have opened three of them. That is not a strategy problem, it is the dread doing its work — and it is worth being honest about, because the fix is not a better opener, it is sending one at all.

**If you are sending, what are they?** Read the last ten. If they could have been sent to anybody, that is the whole answer and track two of this topic is the fix. *Hey*, *how's your week going*, and anything about the weather all fall in this category regardless of how warmly they are phrased.

The other side of it is worth checking too. Matches where they opened and you never replied are the same failure wearing different clothes, and they are easy to lose track of when the app buries a conversation after two days.

And there is a timing element people miss: the first day matters disproportionately. A match answered within a day is a live conversation; a match answered a week later is a stranger writing to somebody who has forgotten swiping right. If your fixed slot from the previous track is once a week, this is the join it costs you, and it is worth adding one short check-in specifically for new matches.

If you keep one thing: read your last ten openers. If any of them could have gone to anybody, you have found it.$md$,
  $j$[
    {
      "situation": "Plenty of matches and no conversations.",
      "line": "(are you sending anything?)",
      "why": "A surprising number of people with this exact complaint have opened three of their matches. That is dread rather than strategy, and the fix is sending one at all."
    },
    {
      "situation": "You are sending, and nothing comes back.",
      "line": "(read the last ten)",
      "why": "If they could have been sent to anybody, that is the whole answer — regardless of how warmly they are phrased."
    },
    {
      "situation": "You check the app once a week.",
      "line": "(that is costing you this join)",
      "why": "A match answered within a day is a live conversation. A week later you are a stranger writing to somebody who has forgotten swiping right."
    }
  ]$j$::jsonb,
  $j$[
    {
      "prompt": "What is the first thing to check?",
      "options": [
        { "text": "Whether your openers are interesting enough.", "correct": false, "note": "Second. Plenty of people with this complaint have not sent anything to check the quality of." },
        { "text": "Whether you are sending anything at all.", "correct": true, "note": "A surprising number have a list of matches and have opened three of them. That is the dread doing its work, and no opener improves it." },
        { "text": "Whether they are real accounts.", "correct": false, "note": "The explanation that removes your own agency, and it is rarely the main cause." },
        { "text": "Whether you matched with the right people.", "correct": false, "note": "You liked them enough to swipe. Re-litigating that is a way of not sending anything." }
      ],
      "explain": "Sending nothing and sending badly look identical in the numbers and need opposite fixes."
    },
    {
      "prompt": "Why does the first day matter so much here?",
      "options": [
        { "text": "They will match with somebody else.", "correct": false, "note": "Possibly, and it frames it as a race. The real reason is about memory rather than competition." },
        { "text": "The app deprioritises old matches.", "correct": false, "note": "Mechanics vary and are not the mechanism you can rely on." },
        { "text": "A week later you are a stranger writing to somebody who has forgotten you.", "correct": true, "note": "A match answered within a day is a live conversation. The same message a week on has to reintroduce itself before it can do anything." },
        { "text": "You will lose your nerve.", "correct": false, "note": "Often true and it is a separate problem, addressed by having a slot at all." }
      ],
      "explain": "If your slot is weekly, add a short check-in for new matches specifically."
    }
  ]$j$::jsonb,
  $j${
    "scale": { "min": 1, "max": 5 },
    "criteria": [
      { "key": "checked_sending", "label": "Checked whether they were sending", "description": "Established the honest baseline first." },
      { "key": "read_ten", "label": "Read the last ten", "description": "Looked at what was actually sent rather than remembering it." },
      { "key": "specific", "label": "Found the generic ones", "description": "Identified openers that could have gone to anybody." },
      { "key": "timing", "label": "Fixed the timing", "description": "Answered new matches within a day." }
    ]
  }$j$::jsonb,
  $j${
    "setting": "Four weeks of numbers: sixty matches, four conversations that got past two exchanges.",
    "partner": {
      "name": "Sam",
      "role": "a friend going through the numbers with you",
      "personality": "Asks to see the actual messages rather than a description of them, and asks how many matches were opened at all.",
      "mood": "Focused.",
      "openness": 5
    },
    "opening_beat": "\"Sixty matches, four conversations. How many of the sixty did you message?\"",
    "success_looks_like": "The user establishes whether the problem is sending or what is sent.",
    "constraints": [
      "Stay in character at all times. Never coach, evaluate or break the scene.",
      "Ask for the count of messages actually sent before discussing their quality.",
      "Ask what the last few said, specifically.",
      "Never write an opener for the user."
    ]
  }$j$::jsonb,
  $md$Today, read the last ten opening messages you sent. Log how many could have been sent to anybody.$md$
),
(
  (select id from public.skills where slug = 'where-it-is-breaking'),
  4,
  'Conversations that fade',
  $md$This is where the whole thing breaks most often, and it is the hardest join to see, because a fading conversation does not feel like a failure — it feels like weather.

Nothing goes wrong. Replies get slower. A message goes unanswered on a Wednesday and neither of you minds. Two weeks later it is over, and it is genuinely difficult to point at a moment where anybody decided anything.

**The move:** check whether you ever actually proposed anything, with a day in it.

That is nearly always the answer, and it is nearly always uncomfortable to discover, because it means the fade was not something that happened to you. Go through your last five conversations and count the ones where you named a place and a day. If the number is zero or one, you have found the join, and no improvement to your messaging will touch it.

The second version is proposing without a day — *we should get a drink sometime* — which produces *yes definitely* and nothing else. That is not a proposal, and both people leave the exchange believing something was arranged, which is why it can happen four times in a row without anybody noticing.

The timing matters as much as the asking. A few days of good exchanges is the moment; a fortnight of them is the fade already in progress. Every message spends a little of the interest that brought you together and none of them replace it, which is why a conversation that has been excellent for three weeks is frequently more finished than one that has been fine for three days.

And the honest note for anybody quiet: this join is where dread does the most damage in the whole topic. Messaging is comfortable, proposing is not, and it is entirely possible to spend six months being very good at the comfortable part while never once doing the thing that produces a date.

If you keep one thing: count your last five conversations for a named day. That number is your actual conversion problem.$md$,
  $j$[
    {
      "situation": "Five conversations, all faded, none of them badly.",
      "line": "(count the ones where you named a day)",
      "why": "Nearly always the answer, and uncomfortable to find, because it means the fade was not something that happened to you."
    },
    {
      "situation": "You said we should get a drink sometime.",
      "line": "(that is not a proposal)",
      "why": "It produces yes definitely and nothing else, and both people leave believing something was arranged — which is why it can happen four times in a row."
    },
    {
      "situation": "Three excellent weeks of messaging.",
      "line": "(more finished than three fine days)",
      "why": "Every message spends a little of the interest that brought you together, and none of them replace it."
    }
  ]$j$::jsonb,
  $j$[
    {
      "prompt": "Why is this join the hardest to see?",
      "options": [
        { "text": "Because the apps hide old conversations.", "correct": false, "note": "A nuisance, and you would still not be able to point at the moment it ended." },
        { "text": "Because a fade feels like weather rather than a failure.", "correct": true, "note": "Nothing goes wrong, replies get slower, and it is genuinely difficult to point at a moment where anybody decided anything." },
        { "text": "Because both people are equally responsible.", "correct": false, "note": "A comfortable framing, and it is the one that stops people checking their own count." },
        { "text": "Because it happens slowly.", "correct": false, "note": "Speed is not the issue. It is the absence of any identifiable decision." }
      ],
      "explain": "Count the conversations where you named a day. That number is the conversion problem."
    },
    {
      "prompt": "Why does a three-week conversation often convert worse than a three-day one?",
      "options": [
        { "text": "You know too much about each other.", "correct": false, "note": "Rarely the problem, and knowing somebody usually helps." },
        { "text": "One of you has lost interest by then.", "correct": false, "note": "Circular — that is the thing being explained rather than the explanation." },
        { "text": "Every message spends interest and none replace it.", "correct": true, "note": "Which is why a conversation that has been excellent for three weeks is frequently more finished than one that has been fine for three days." },
        { "text": "The novelty wears off.", "correct": false, "note": "The same observation with less precision, and it does not tell you when to act." }
      ],
      "explain": "A few good days is the moment. A fortnight of them is the fade already running."
    }
  ]$j$::jsonb,
  $j${
    "scale": { "min": 1, "max": 5 },
    "criteria": [
      { "key": "counted", "label": "Counted the proposals", "description": "Checked how many conversations contained a named day." },
      { "key": "honest", "label": "Was honest about it", "description": "Accepted that the fade was not something that happened to them." },
      { "key": "a_day", "label": "Proposed with a day", "description": "Stopped treating sometime as an ask." },
      { "key": "timing", "label": "Moved earlier", "description": "Proposed within days rather than weeks." }
    ]
  }$j$::jsonb,
  $j${
    "setting": "Four weeks of numbers: fourteen real conversations, no dates arranged. All of them faded pleasantly.",
    "partner": {
      "name": "Sam",
      "role": "a friend going through the numbers with you",
      "personality": "Asks how many of the fourteen contained an actual proposal with a day in it, and waits for a real count.",
      "mood": "Direct.",
      "openness": 5
    },
    "opening_beat": "\"Fourteen conversations, no dates. In how many of them did you name an actual day?\"",
    "success_looks_like": "The user counts honestly and identifies the missing proposal.",
    "constraints": [
      "Stay in character at all times. Never coach, evaluate or break the scene.",
      "Ask for a number and do not accept a description of how the conversations felt.",
      "Treat we should do something as not counting, and say so if it comes up.",
      "Never tell the user what to send."
    ]
  }$j$::jsonb,
  $md$Today, look back at the last five you had and count how many contained an actual named day. Log the number.$md$
),
(
  (select id from public.skills where slug = 'where-it-is-breaking'),
  5,
  'Dates, but no second dates',
  $md$If the numbers say you are matching, talking and meeting people, and none of it becomes a second date, then this topic has nothing left to offer you — and saying so is more useful than another lesson about photographs.

**The move:** stop working on the app, and go and work on the two hours.

This is worth being firm about, because the temptation runs the other way. The app is the part with settings, numbers and an edit button, so it is where people take a problem that lives somewhere else entirely — and rewriting a profile that has demonstrably produced dates is one of the more common ways to spend a wasted year.

The diagnosis is clean. Matching means the profile works. Conversations means the messaging works. Dates arranged means the asking works. Three joins in a row functioning is not somewhere to look for a fault. Whatever is happening is happening in a room, in person, over about two hours — which is a completely different skill from everything in this topic, and it is the subject of The first date.

Two possibilities are worth separating before you go, because they need different things. If they are not turning into second dates because *you* did not want one, the app is working perfectly and you are being introduced to people who are not right — which is a slower problem about who you are choosing rather than a skill problem at all. If they are not turning into second dates because *they* did not want one, that is the two hours, and it is learnable in a way people assume it is not.

The unglamorous checks come first either way: are you proposing the second one, and are you doing it while the first is still fresh? A surprising number of people who believe dates go badly are simply not asking afterwards, which is the same fade one stage further along.

If you keep one thing: three working joins means the problem is not here. Go and read the other topic.$md$,
  $j$[
    {
      "situation": "Matching, talking, meeting — and no second dates.",
      "line": "(three working joins means it is not the app)",
      "why": "Matching means the profile works, conversations mean the messaging works, dates mean the asking works. That is not somewhere to look for a fault."
    },
    {
      "situation": "You are about to rewrite the profile again.",
      "line": "(it has demonstrably produced dates)",
      "why": "The app has settings and an edit button, so people bring it problems that live somewhere else. This is one of the commonest ways to waste a year."
    },
    {
      "situation": "You have not asked any of them for a second date.",
      "line": "(that is the fade, one stage later)",
      "why": "A surprising number of people who believe their dates go badly are simply not asking afterwards."
    }
  ]$j$::jsonb,
  $j$[
    {
      "prompt": "Three joins working and the fourth failing. Where is the problem?",
      "options": [
        { "text": "Somewhere in the profile, still.", "correct": false, "note": "It produced matches, conversations and dates. That is a working profile by every available measure." },
        { "text": "In the two hours, which is a different topic.", "correct": true, "note": "Whatever is happening is happening in a room, in person — a completely different skill from everything here, and the subject of The first date." },
        { "text": "In who you are matching with.", "correct": false, "note": "One of the two possibilities and only if you are the one not wanting a second date. Worth separating rather than assuming." },
        { "text": "Nowhere — that is just how it goes.", "correct": false, "note": "It is learnable, and treating it as luck is how people stay stuck at this join for years." }
      ],
      "explain": "The app is the part with an edit button, which is why problems from elsewhere get taken to it."
    },
    {
      "prompt": "What is worth checking before you go?",
      "options": [
        { "text": "Whether you are proposing the second one at all.", "correct": true, "note": "A surprising number of people who believe their dates go badly are simply not asking afterwards — the same fade, one stage further along." },
        { "text": "Whether your photos look like you.", "correct": false, "note": "Worth doing generally and it does not explain a pattern that survives three working joins." },
        { "text": "Whether you are meeting too soon.", "correct": false, "note": "The opposite risk is the documented one. Meeting early is what stops you building somebody." },
        { "text": "Whether you are picking the wrong venues.", "correct": false, "note": "Genuinely matters and is a first-date question, which is where this lesson is sending you anyway." }
      ],
      "explain": "Ask, and ask while the evening is still fresh. Then go and read the other topic."
    }
  ]$j$::jsonb,
  $j${
    "scale": { "min": 1, "max": 5 },
    "criteria": [
      { "key": "diagnosed", "label": "Diagnosed correctly", "description": "Recognised three working joins and stopped looking here." },
      { "key": "stopped_editing", "label": "Stopped editing the profile", "description": "Did not take an in-person problem to the app." },
      { "key": "separated", "label": "Separated the two cases", "description": "Distinguished not wanting one from not being offered one." },
      { "key": "asked", "label": "Checked they were asking", "description": "Made sure the second date was actually proposed." }
    ]
  }$j$::jsonb,
  $j${
    "setting": "Four weeks of numbers: plenty of matches, good conversations, five first dates arranged, four of them happened, none led to a second.",
    "partner": {
      "name": "Sam",
      "role": "a friend going through the numbers with you",
      "personality": "Reads the funnel from the top, notices that everything works until the last join, and asks what the user is planning to change.",
      "mood": "Amused when the answer is the profile.",
      "openness": 5
    },
    "opening_beat": "\"Four dates in a month. So what exactly are you planning to fix on the app?\"",
    "success_looks_like": "The user recognises the problem is not in this topic.",
    "constraints": [
      "Stay in character at all times. Never coach, evaluate or break the scene.",
      "Point out which joins are working whenever the user proposes an app-side fix.",
      "Ask whether they proposed a second date at all.",
      "Never diagnose the in-person problem yourself."
    ]
  }$j$::jsonb,
  $md$Today, work out which of your four joins is actually failing. Log the join, and what you are going to do about it.$md$
);

create or replace function pg_temp.set_mode(
  p_skill text, p_order integer, p_mode text, p_spec jsonb
) returns void language sql as $fn$
  update public.lessons l
    set rehearsal_mode = p_mode, rehearsal_spec = p_spec
    from public.skills s
    where l.skill_id = s.id and s.slug = p_skill and l.sort_order = p_order;
$fn$;

select pg_temp.set_mode('where-it-is-breaking', 1, 'choice', $j${
  "beats": [
    {
      "situation": "Four months in. It is not working, you do not know why, and you have rewritten the profile six times.",
      "prompt": "What is missing?",
      "options": [
        { "text": "Better photos.", "correct": false, "note": "Maybe. You have a one-in-four chance of that being the broken join, and people do not guess evenly — they guess the part they can edit from the sofa." },
        { "text": "Numbers.", "correct": true, "note": "Without them you are working from a feeling generated by whatever happened last, and that feeling reliably points at the profile." },
        { "text": "Patience.", "correct": false, "note": "Four months is not impatience. It is four months of acting on impressions." },
        { "text": "More swipes.", "correct": false, "note": "Possibly the answer and you cannot know that yet, which is the point." }
      ]
    },
    {
      "situation": "You had a terrible week and are about to change your main photo.",
      "prompt": "Is that enough to act on?",
      "options": [
        { "text": "Yes — a bad week is data.", "correct": false, "note": "The numbers are small enough that a single match distorts everything. One week is noise in both directions." },
        { "text": "Yes, if it felt notably worse than usual.", "correct": false, "note": "Feeling worse than usual is exactly the signal that is unreliable here." },
        { "text": "No — but change it anyway, it costs nothing.", "correct": false, "note": "It costs the reading. Change something now and you will not know what produced whatever happens next." },
        { "text": "No. Four weeks, then decide.", "correct": true, "note": "A week that felt terrible is not evidence of a problem and a week that felt great is not evidence of a fix." }
      ]
    }
  ]
}$j$::jsonb);

select pg_temp.set_mode('where-it-is-breaking', 2, 'choice', $j${
  "beats": [
    {
      "situation": "Four weeks of numbers: six hundred swipes, eleven matches. The conversations that did start went fine.",
      "prompt": "Which join is broken?",
      "options": [
        { "text": "The first one — matching.", "correct": true, "note": "Everything downstream is working. Eleven from six hundred is the join to look at, and it is the one time the answer genuinely is the profile." },
        { "text": "The openers — eleven matches should produce more.", "correct": false, "note": "You said the conversations went fine. That join is working." },
        { "text": "Volume — six hundred is not many.", "correct": false, "note": "Worth checking and six hundred is a reasonable month. If it were sixty, this would be the answer." },
        { "text": "Impossible to say from these numbers.", "correct": false, "note": "This is exactly what the numbers are for. One join is visibly out of line with the rest." }
      ]
    },
    {
      "situation": "You have decided the profile is the problem.",
      "prompt": "What do you change?",
      "options": [
        { "text": "All of it — start again properly.", "correct": false, "note": "Then something improves and you have no idea what. You are guessing again next month." },
        { "text": "The prompts, so there is more to reply to.", "correct": false, "note": "They matter after a match. A large proportion of people never scroll that far." },
        { "text": "The first photo. Nothing else, for two weeks.", "correct": true, "note": "The decision is made in about two seconds and mostly on that image. One change at a time is the only way to learn what worked." },
        { "text": "Add more photos.", "correct": false, "note": "Four good ones beat six of anything, and quantity is not the failing here." }
      ]
    }
  ]
}$j$::jsonb);

select pg_temp.set_mode('where-it-is-breaking', 3, 'line', $j${
  "says": "Sixty matches, four conversations. How many of the sixty did you actually message?",
  "model": {
    "line": "Nine, I think. So it is not really the openers, is it — it is that I am not sending them.",
    "why": "The honest baseline first. Sending nothing and sending badly look identical in the numbers and need opposite fixes, and no improvement to an opener helps if there is not one."
  },
  "checks": [
    { "kind": "forbids_any", "requirement": "Answer with a count, not an impression",
      "words": ["most of them", "quite a few", "a fair number", "loads", "not many really", "hard to say", "i think most"] },
    { "kind": "min_words", "requirement": "Say the number and what it means", "n": 8 },
    { "kind": "max_words", "requirement": "A reading, not an essay", "n": 40 }
  ]
}$j$::jsonb);

select pg_temp.set_mode('where-it-is-breaking', 4, 'line', $j${
  "says": "Fourteen conversations, no dates. In how many of them did you name an actual day?",
  "model": {
    "line": "One. And even that was a maybe we should sometime, so realistically none.",
    "why": "The count people least want to do, and it is nearly always the answer. It also means the fade was not something that happened to them."
  },
  "checks": [
    { "kind": "forbids_any", "requirement": "Count, do not describe",
      "words": ["a few", "some of them", "most", "several", "hard to say", "it varies", "they just fizzled", "they lost interest"] },
    { "kind": "min_words", "requirement": "Say the number", "n": 6 },
    { "kind": "max_words", "requirement": "Short and honest", "n": 35 }
  ]
}$j$::jsonb);

select pg_temp.set_mode('where-it-is-breaking', 5, 'choice', $j${
  "beats": [
    {
      "situation": "A month of numbers: plenty of matches, good conversations, five dates arranged, four happened, none led to a second.",
      "prompt": "What do you fix?",
      "options": [
        { "text": "The profile — clearly something is off.", "correct": false, "note": "It produced matches, conversations and four dates in a month. That is a working profile by every available measure." },
        { "text": "Nothing here. The problem is in the two hours.", "correct": true, "note": "Three joins in a row functioning is not somewhere to look for a fault. Whatever is happening is happening in a room, which is a different topic entirely." },
        { "text": "Who you are matching with.", "correct": false, "note": "One of two possibilities, and only if you are the one not wanting a second. Worth separating rather than assuming." },
        { "text": "Meet them sooner, before the messaging goes stale.", "correct": false, "note": "You are already meeting them. That join is working." }
      ]
    },
    {
      "situation": "Before you go and work on the in-person part.",
      "prompt": "What is worth checking first?",
      "options": [
        { "text": "Whether they enjoyed the dates.", "correct": false, "note": "Unknowable, and asking after the fact tends to produce politeness rather than information." },
        { "text": "Whether your photos look like you in person.", "correct": false, "note": "Worth doing generally, and it does not explain a pattern that survives three working joins." },
        { "text": "Whether you proposed a second one at all.", "correct": true, "note": "A surprising number of people who believe their dates go badly are simply not asking afterwards — the same fade, one stage further along." },
        { "text": "Whether you are meeting the right kind of person.", "correct": false, "note": "The other of the two possibilities, and it only applies if you did not want a second date either." }
      ]
    }
  ]
}$j$::jsonb);
