-- Proofreading pass, topic 2 of 11: Interviews, part one — quotation style.
--
-- Interviews was the only topic in the app that used double quotes for speech:
-- 130 quoted spans against 1 across the other ten topics, which use italics
-- exclusively. It was not a rule being applied either — lesson 2.4 italicises
-- one candidate line and quotes the next, and single words like "we" and
-- "impact" are quoted where every other topic italicises them.
--
-- Settled now rather than after translation, because italics survive a
-- translation untouched while quotation marks do not: German sets them „so",
-- Spanish «so» or with a dash. Leaving it would mean normalising the same
-- inconsistency once per language instead of once.
--
-- Scope is prose only — theory, takeaways, descriptions. Two conventions are
-- genuinely app-wide and are left exactly as they are: scenario.opening_beat
-- wraps the partner's spoken line in quotes in all eleven topics, and the
-- situation fields quote reported speech the same way everywhere.
--
-- Generated by pairing quotes (odd opens, even closes) rather than by pattern
-- replacement, which would have corrupted the text — several cards contain
-- runs like `switch to "I" for everything you did, then "I took the payments
-- half"`, where a naive match spans the gap between two quotations. All 114
-- fields were balanced, and each conversion was verified to change nothing but
-- the marks: text identical once marks are stripped, bold counts unchanged, no
-- stray *** produced, and no span left opening or closing on whitespace.
--
-- 51 fields, 148 spans.

update public.skills set description = '*Tell me about yourself* — the question you will always be asked, and the one most people improvise.' where slug = 'interview-your-story';

update public.lessons l set theory_md = '*Tell me about yourself* is not a question. It is a slot, and you decide what goes in it.

Most people answer it chronologically, because a life arrives in that order. Chronology is a trap: it spends the first thirty seconds on a degree you finished eleven years ago, and the interviewer''s attention is highest in exactly those thirty seconds.

Use three beats instead.

**Beat one — where you came from.** One sentence. The shortest possible account of how you ended up doing this kind of work at all. Not where you were born. Not your A-levels.

**Beat two — what you did with it.** The middle, and the only part that should be more than a sentence or two. One or two concrete things you have actually done, chosen because they resemble the job on the table.

**Beat three — why you are here.** The landing. Why this role, at this place, now.

**The move:** answer in three beats — where you came from, what you did with it, why you are in this room.

The reason this works is not that it is tidy. It is that the interviewer is trying to build a model of you while you talk, and three beats is a model they can hold. A chronology gives them a list, and a list has no shape, so they remember the last thing you said and nothing else.

One warning. Beat two is where the good material lives, so it wants to grow, and it will keep growing until the answer is four minutes long and beat three never arrives. Beat three is the one that does the work. Protect it.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-story' and l.sort_order = 1;

update public.lessons l set theory_md = 'Two candidates give the same middle. One ends on the last thing they did. The other ends on the job in the room. The second one is remembered as a better candidate, and neither of them ever finds out why.

The landing does something no other part of the answer can. Everything before it is evidence, and evidence does not interpret itself. The interviewer is sitting there quietly asking *so what*, and the landing is where you answer that out loud instead of hoping.

A landing has two halves, and skipping either is what makes it feel weak.

**Why this work.** What you are actually reaching for, in plain language. Not a compliment about the company — a direction. *I want to be doing this on a bigger surface* is a direction. *You are the market leader* is flattery, and flattery is free, so it counts for nothing.

**Why here.** One specific thing about this place that could not be said about their nearest competitor. It does not have to be profound. A product decision you noticed, the way the role is written, something the person interviewing you built.

**The move:** finish on why this work and why here, with one detail that could only be about them.

The specific detail is the part people skip, and it is the part that is remembered. Interviewers spend all day being told they are an exciting company. Being told that someone noticed the thing they actually did is rare enough to be worth a note in the margin.

One caution: the landing must be true. A fabricated reason for wanting the job is the single easiest thing to catch, because the follow-up question is always *say more about that*, and there is no more.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-story' and l.sort_order = 2;

update public.lessons l set theory_md = 'Nobody has ever been rejected for a story that was too short.

The reason ninety seconds is the target is not that attention spans are short. It is that an interview is a conversation with a budget, and every second you spend is a second not spent on a question where you could have been more impressive. A four-minute answer to the opener does not just bore them — it eats the part of the hour where you would have shone.

The instinct when cutting is to trim evenly: shave a bit off each part, speak a little faster, drop some adjectives. This produces a compressed version of the same answer, which is worse, because it is now dense as well as long.

Cut whole things instead.

**Drop the second-best example.** Two examples that both prove the same point are one example and a hostage. Keep the one that most resembles the job.

**Drop every job that is not load-bearing.** You are not obliged to mention all of them. *A couple of agency roles before that* covers four years and nobody will stop you.

**Drop the reasons.** Why you left each place, why you took the next one — that is a separate answer, for a question they may not even ask. Explaining transitions unprompted is the single biggest hidden cost in most stories.

**The move:** cut whole items, never words — the second-best example goes first.

The test for whether it worked is not the clock. It is whether the interviewer asks a follow-up. A story that ends with them wanting one specific thing expanded is a story that did its job; you get to talk about your best material as an answer to their question, which lands twice as hard as volunteering it.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-story' and l.sort_order = 3;

update public.lessons l set theory_md = 'The same story told to a recruiter, a hiring manager and a panel should not be the same story. Not because you are being slippery — because they are asking different questions with the same words.

**A recruiter** is asking: does this person match the brief, and are they normal. They are not equipped to assess your craft and they are usually screening a lot of people. Pitch high, use the words from the advert, keep it short. Detail is a cost here, not a virtue.

**A hiring manager** is asking: what will this person be like to work with on the thing I am currently struggling with. They want the middle beat, they want it concrete, and they want to hear the messy version — what was actually hard.

**A panel or a skip-level** is asking: does this person see the bigger picture, and could they grow. Pitch to scope. The middle beat becomes about the size of what you owned rather than the detail of how you did it.

**The move:** keep the three beats, and change only the middle to fit who is asking.

What must not change is the landing. Your reason for wanting this job should be identical in every room, and if it drifts between conversations you will be caught, because they compare notes — that is what the debrief is.

A last one, cheap and effective: use their vocabulary. If the advert says *partners* rather than *clients*, say partners. It is not sycophancy, it is evidence that you can be understood inside their building.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-story' and l.sort_order = 4;

update public.lessons l set theory_md = 'This is a different question wearing the same coat, and answering it with your prepared story is one of the most common ways a good candidate stumbles.

*Tell me about yourself* wants a shape. *Walk me through your CV* wants a chronology — they are holding the document and following along, and if you jump around they lose their place. Give them the chronology. But give it with a spine.

The spine is one sentence, said before you start: what the whole arc adds up to. *The short version is that I keep ending up as the person who fixes reporting.* Then walk the roles, briefly, and every role gets one line about why the move happened. Now the chronology is evidence for a claim rather than a list.

**The move:** state what the arc adds up to, then walk it, giving each move a reason.

Two specific things to prepare, because this is the question where they surface.

**The jumps.** Short stays, sideways moves, a redundancy, a gap. Say them plainly and in the same tone as everything else. The tone is what gets read, not the fact — a nine-month role explained calmly is a nine-month role, and one explained apologetically is a problem.

**The oldest stuff.** Anything more than about eight years back gets a clause, not a paragraph. If they want it, they will stop you, and being stopped is fine.

The interviewer''s actual question underneath all this is: does this person''s career make sense, and are they telling me the truth about it. Both are answered by tone as much as content.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-story' and l.sort_order = 5;

update public.lessons l set theory_md = 'Nobody asking this believes you have a plan, and nobody wants to hear one.

They are checking two things. That the road you are already on runs through this job, and that you are not going to leave in eight months. Both are answerable, and neither of them needs a title.

**The move:** describe the direction you are already travelling, not the destination.

Titles are the trap. Naming their job is a threat, naming a job above it is a strange thing to say to somebody who would be your manager, and naming a job below it makes them wonder why you applied. A direction has none of those problems, and it has one large advantage: it can be checked against your CV, which is what makes it believable.

*More of this, less of that* is a complete answer. So is *the same work, on problems where nobody knows the answer yet*. Both say something real about you and neither commits you to anything you would have to remember.

If you genuinely do not know, say that and give the direction anyway. Not knowing the destination is normal. Not knowing the direction reads as drifting.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-motivation' and l.sort_order = 2;

update public.lessons l set theory_md = 'The generic answers fail for a specific reason: they cannot be wrong.

*I like solving problems. I am motivated by impact. I enjoy a challenge.* Nobody in the history of interviews has said the opposite, which means these sentences carry no information, and an interviewer who has asked this four times today can hear that immediately.

**The move:** name the thing that already explains your CV.

A real motivation is checkable, and the place it is checked is the page in front of them. It should account for something that would otherwise look odd — why you stayed somewhere two years longer than made sense, why you took a sideways move, why you keep ending up on the same kind of mess. If your answer explains nothing on your CV, it is a value statement rather than a motivation.

This is also the most useful question in the interview for you, because working out the true answer tells you whether you want the job. A motivation you can name is one you can check the role against.

Specific and slightly odd beats admirable. *I like finding out why something is actually happening* is a better answer than *impact*, and it is a better answer partly because nobody else will give it.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-motivation' and l.sort_order = 4;

update public.lessons l set theory_md = 'This question is doing two jobs and both of them are reasonable.

The first is timing: how long have they got before you are gone. The second is calibration: what else do you consider comparable, which tells them how you see the role and sometimes tells them their salary band is wrong.

**The move:** answer honestly at a level of detail you choose, and never invent an offer.

Naming companies is optional and rarely necessary. Naming the shape is what is useful to both of you — two others at a similar stage, or one further along, or nothing yet because you only started looking. Any of those is a complete answer, and *nothing yet* is not a weakness however it feels.

The invented competing offer is the one genuinely dangerous move in this whole topic. It is checkable in a small industry, it sets a deadline you made up and then have to live inside, and if anybody calls it — *great, when do you need to decide?* — you have nothing. The upside is a few thousand pounds. The downside is the offer.

Telling them about a real deadline is different, and worth doing early rather than as leverage.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-motivation' and l.sort_order = 5;

update public.skills set takeaway_md = 'Every behavioural question is the same question: show me you have done this before.

The structure everyone teaches is fine and nobody notices it when it is done well. What they notice is the ratio. Most people spend two-thirds of the answer setting the scene, because the scene is the comfortable part, and then run out of road before the bit that would have got them hired. Two sentences of scenery, then the action, then the result.

*We* is the word that costs you the job. It is honest, it is how you talk at work, and in an interview it makes you invisible — the interviewer cannot hire the team. Say what the team did once, then say what you did inside it.

Finish on a number wherever an honest one exists, and where it does not, finish on the change: what was true afterwards that was not true before. An answer that ends on the action alone sounds like effort. An answer that ends on the outcome sounds like impact.

If you keep one thing: cut the setup in half, and give the time to the verb.' where slug = 'interview-evidence';

update public.lessons l set theory_md = '*Tell me about a time when…* is an invitation to prove something, and most people spend the invitation on set dressing.

Watch what happens to an untrained answer. Thirty seconds establishing the company, the team structure, the quarter it happened in, who reported to whom. Then the interviewer''s follow-up question arrives before the good part, or the candidate notices the time and rushes the ending. The material was there. It never got out.

The scene exists only so the rest makes sense. Two sentences: what the situation was, and why it was hard. That second half is the one people skip, and it is the one that makes everything after it count — an interviewer cannot be impressed by a solution to a problem they do not know was difficult.

**The move:** two sentences of scene, one of which says why it was hard, then go straight to what you did.

The proportions to aim for, out of roughly two minutes: fifteen seconds of scene, sixty of action, fifteen of result, and the rest is breathing.

If you find yourself explaining the org chart, you have gone wrong. Nobody is being hired on the strength of their old company''s reporting lines.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-evidence' and l.sort_order = 1;

update public.lessons l set theory_md = '*We* is the most expensive word in an interview.

It is not a lie and it is not modesty. It is how people talk about work, because work is done by teams and taking sole credit feels grubby. But the interviewer cannot hire the team. Every time an achievement is attributed to *we*, it goes into a bucket the interviewer cannot use, and a candidate who says *we* throughout comes out of the room having described a good company rather than a good candidate.

The fix is not to claim more. It is to be precise about the boundary.

Say what the team did, once, in the scene: *the team was rebuilding the checkout.* Then switch to *I* for everything you personally did, and stay there. *I took the payments half. I found that the retry logic was double-charging about one in four hundred. I wrote the fix and I sat with support for a week to catch the ones we had already sent out.*

That is honest. Nothing has been stolen from anyone. The interviewer now has something to assess.

**The move:** the team gets one sentence in the scene; everything after it is *I*.

There is a second-order version of this worth knowing. If you led the work, *I* is not enough — leadership shows up in verbs about other people. *I got the two teams to agree on one owner.* *I talked the head of support out of the manual process.* Those are I-sentences that are visibly about a group, and they are the strongest evidence of seniority there is.

Watch for the passive voice too, which is *we* in disguise. *The decision was taken to postpone* is a sentence with nobody in it.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-evidence' and l.sort_order = 2;

update public.lessons l set theory_md = 'An answer that stops at the action sounds like effort. An answer that ends on the change sounds like impact. The words in between can be identical.

Most people end their stories where the work ended, because that is where their memory of it ends. But the interviewer is not scoring the work. They are scoring what happened because of it, and if you do not tell them, they will assume it was fine and forget the story.

The strongest ending is a number, and the number does not have to be impressive. *It went from about a day to about ten minutes* is a good number. So is *we stopped losing roughly one order a week.* Precision beats magnitude — an honest small number is more persuasive than a large vague one, because a large vague one sounds like the number a person reaches for when they have none.

If there is no honest number, end on a change of state. What was true afterwards that was not true before. *Nobody has had to do that by hand since.* *The two teams still use the same definition, three years later.* That last kind — the thing that outlived you — is the best ending available, because it proves the fix was real rather than heroic.

**The move:** finish on what was different afterwards, with a number if you honestly have one.

Never invent the number. Interviewers ask how it was measured surprisingly often, and there is no recovering from not knowing where your own figure came from. *I never got a clean measure of it, but…* is a completely acceptable sentence and it costs you almost nothing.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-evidence' and l.sort_order = 3;

update public.lessons l set theory_md = 'There are perhaps forty behavioural questions in common use and they are asking about six things. Prepare stories, not answers.

Six pieces of work, chosen so that between them they cover: something you delivered under constraint, something you fixed that was broken, a conflict with another person, a failure, something you led or influenced without authority, and something you learned or changed your mind about.

Most good stories serve three or four of those. The conflict story is often also the influence story. The failure is usually also the learning. That is not cheating — the interviewer is asking about a facet of you, and the same piece of work can show several.

**The move:** hold six stories in your head, and pick the facet the question asked about.

The skill in the room is not recall, it is aiming. The same story about a delayed launch is a delivery story if you tell the part about re-scoping, a conflict story if you tell the part about the argument with sales, and a failure story if you tell the part where you shipped anyway and it broke. Same events, three answers, and the aiming happens in the first sentence: *The part of this that is about disagreement is…*.

Two rules that keep this honest. Do not use the same story twice in one interview — it makes a career look thin even when it is not. And do not force a story onto a question it does not fit; a candidate answering the question they prepared instead of the one they were asked is the most visible failure mode there is, and interviewers score it harshly.

Keep them recent. A brilliant story from nine years ago raises the question of what you have done since.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-evidence' and l.sort_order = 4;

update public.lessons l set theory_md = 'Sooner or later they ask for an example of something you have not done. The instinct is to stretch something adjacent until it covers, and the stretch is always audible.

There are three honest routes out, and picking the right one is most of the skill.

**The adjacent example, labelled.** *I have not managed people directly. The closest is that I ran a team of four contractors for eight months, which had most of the same problems and none of the authority.* The label is what makes this work. An adjacent example offered as if it were the real thing gets caught; the same example offered with its limits stated is often better received than a genuine one, because it demonstrates that you know the difference.

**The honest no, plus the shape of how you would approach it.** *No, I have never run a migration that size. If I were, the first thing I would want to know is whether we could do it in slices.* A clean no followed by a real answer to the underlying question. What they are testing is usually the thinking, not the credential.

**The transferable, from outside work.** Volunteering, sport, a side project, family. Weaker for technical claims, often strong for questions about conflict, organisation or persuasion.

**The move:** say what you have not done, then answer the question underneath it.

What sinks candidates here is not the gap. It is the flannel — the answer that is neither yes nor no, that circles for ninety seconds hoping to be mistaken for a yes. Interviewers are extremely well calibrated to this. It reads as evasive, and it converts a small gap into a question about your honesty, which is a much larger problem.

One line worth having ready: *Not yet.* It is a complete answer, it is confident, and it invites the follow-up you want.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-evidence' and l.sort_order = 5;

update public.skills set takeaway_md = 'These questions are not traps, and treating them as traps is what springs them.

The interviewer is checking two things: whether you can see yourself clearly, and whether you are safe to give bad news to. A polished non-answer fails both at once. *I work too hard* tells them you will not tell them when a project is late.

The shape that works is short. Name the real thing, in one sentence, without flinching. Say what it cost — an actual consequence, because a weakness with no cost is a boast wearing a hat. Then say what you changed, and be specific enough that it sounds like a thing you did rather than a lesson you learned. Then stop talking, which is the hardest part, because the silence afterwards feels like it needs filling and filling it is what turns a good answer into a confession.

Gaps work the same way. A year out is a fact, not a charge. State it, say what it was for, move on. The apologising is what makes it sound like something to apologise for.

If you keep one thing: they are not deciding whether you have flaws. They know. They are deciding whether you know.' where slug = 'interview-failure';

update public.lessons l set theory_md = '*Tell me about a time you failed* is not asking whether you have failed. Everyone has. It is asking whether you can look at it without either flinching or performing.

There is a shape that works, and it is four moves long.

**Name it.** One sentence, plainly, in the active voice, with you in it. *I shipped a pricing change that undercharged about six hundred customers for a month.*

**Cost it.** What it actually cost — money, time, someone''s trust, your own credibility. This is the move people skip, and skipping it is what makes a failure answer sound like a humblebrag. A failure with no consequence was not a failure.

**Change it.** What you did differently afterwards, specific enough to be checkable. Not *I learned to be more careful*. *I now write the rollback before the release, not after.*

**Stop.** The hardest one. The silence after a failure story feels enormous from the inside and normal from the outside, and the instinct to fill it is what produces the second, unnecessary confession.

**The move:** name it, say what it cost, say what changed, then stop talking.

Two failure modes to avoid. The disguised success — *I was too ambitious with the timeline* — which everyone recognises and nobody rewards. And the catastrophe, the story so bad that the interviewer starts wondering about liability. The sweet spot is a real failure with a bounded cost, told without drama.

Choose something you have genuinely finished thinking about. A failure you are still defensive about will show, and the defensiveness is what gets scored, not the failure.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-failure' and l.sort_order = 1;

update public.lessons l set theory_md = 'The weakness question survives, despite everyone agreeing it is a bad question, because the answers are so revealing. Not about the weakness — about whether the candidate is willing to be a real person for thirty seconds.

A usable answer needs three properties.

**It is true.** You will be asked a follow-up. Invented weaknesses have no second layer.

**It costs something visible.** *I am impatient* is a start; *I am impatient, and it means I have twice pushed a decision through before a quieter colleague had said their piece* is an answer. The cost is what proves you have looked at it.

**It is not the job.** Do not offer a weakness that is the central requirement of the role. Saying you struggle to prioritise, in an interview for a job that is entirely prioritisation, is honesty aimed at your own foot.

**The move:** name a true weakness, name what it has cost someone else, then name the specific guard you use against it.

That last part matters and it is not the same as fixing it. Most real weaknesses are not fixed, they are managed, and saying so is more credible than claiming a cure. *I have not stopped being impatient. I have started asking the quietest person in the meeting what they think, before I say what I think.*

A note on the too-honest end. Interviewers have a rough threshold: a weakness that makes you harder to work with is fine, and one that makes you unsafe to employ is not. *I find it hard to ask for help* is inside the line. *I lose my temper with people* is not, no matter how well you manage it.

And keep it to one. A candidate who offers three weaknesses has stopped answering a question and started unburdening.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-failure' and l.sort_order = 2;

update public.lessons l set theory_md = 'A gap on a CV is a fact with dates either side of it. It becomes a problem in exactly one circumstance: when the tone of the explanation says it is one.

Interviewers are not scoring the event. They are scoring three things underneath it — is the account consistent, is there bitterness, and would this happen here. Answer those and the fact itself almost never matters.

**Consistent.** The reason you give should be the same reason you gave the recruiter and the same reason on the form. Variation is what turns a question into a line of questioning.

**Unbitter.** This is the one that sinks people. A redundancy or a firing has a villain in it, and the villain is real, and naming them costs you the job. Not because interviewers side with the old employer, but because a candidate who is still angry is a candidate who will be angry about them one day.

**Unlikely to recur.** Say what was specific about the situation. Not a promise, a fact: *The office closed.* *It was a nine-month contract and it ended after nine months.*

**The move:** state the fact with its dates, give one unbitter sentence of reason, and move on at the same pace as the rest of the conversation.

Being let go for performance is the hardest version, and it has one honest structure: it was not working, here is my share of why, here is what I would do differently. Your share has to be real. *It was a bad fit* with no ownership in it is heard as a refusal to look.

Length is the tell. Two sentences reads as a fact. Ninety seconds reads as a wound, whatever the words are.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-failure' and l.sort_order = 3;

update public.lessons l set theory_md = '*Tell me about a time you received difficult feedback* is a question about what happens to you when someone challenges you, and there is no way to answer it in the abstract. The story has to have a moment in it where you were wrong and somebody said so.

The three-part shape.

**What they said, in their words.** Quoting the feedback is what makes this real. *My manager told me I was the reason two people had stopped raising problems in stand-up.* Paraphrasing it upwards — *I got some feedback about my communication style* — is the sound of an answer that has been sanded down.

**What you did with it first.** Including the bit where you did not like it. Nobody receives hard feedback gracefully in the first hour, and claiming to did not happen. *I thought it was unfair for about a day* is a sentence that makes the rest believable.

**What actually changed.** Behaviour, not attitude. Something an observer could have noticed.

**The move:** quote the feedback in their words, admit the first reaction, then say what an observer would have seen change.

The version of this question that catches people is when the feedback was wrong. It happens. The answer is not to pretend you accepted it — it is to show you took it seriously enough to check. *I asked two other people whether they saw the same thing. One did, one did not, and the one who did was more specific, so I went with that.*

Avoid the story where the feedback was trivially easy to accept. If the feedback did not sting, it is not an answer to this question, and choosing a painless one is itself a signal.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-failure' and l.sort_order = 4;

update public.lessons l set theory_md = 'This question sounds like a softer version of the failure question. It is not — it is the seniority test hiding in the friendliest possible wording.

The reason is that there are two levels of answer, and the difference between them is exactly the difference between doing a job and being trusted to run one.

**First-order:** what you would have done differently in the task. *I would have tested it on more devices.* True, fine, forgettable. It says you can spot a mistake after it has been pointed out.

**Second-order:** what you would have done differently about the conditions that produced the mistake. *I would not have agreed to a date before we had seen the data. The testing gap was a symptom — the actual error was accepting a deadline in a meeting where I was the only one who knew it was tight.*

The second answer is not cleverer, it is further back. It looks at the process, the decision, the moment of agreement, rather than at the execution.

**The move:** answer about the conditions that made the mistake likely, not about the mistake.

Two things that strengthen it further. Naming the cost of the alternative — the second-order fix usually has one, and admitting it (*we would have shipped three weeks later, and I think that was the right trade*) shows you are weighing rather than wishing. And saying what you have actually done since, because a reflection with no consequence is an opinion.

The failure mode here is the answer that would do everything differently. A candidate who rewrites the whole project sounds like someone with no judgement about which decision mattered. Pick one.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-failure' and l.sort_order = 5;

update public.skills set takeaway_md = 'Depth is not demonstrated by vocabulary. It is demonstrated by knowing which detail matters.

Assume a mixed room, because it usually is: the person who will do your job, the person who will manage you, and someone from another function who is there for the culture read. Explain it so the last of those three follows you, and the first will not think less of you for it — they will think you can talk to stakeholders, which is the thing their team is short of.

Then offer the depth rather than pouring it. *I can go into how the migration actually worked, if that is useful* hands them the control and tells them there is more where that came from. It also stops the answer that runs for four minutes while the panel waits for a gap.

The single strongest move in this whole skill is naming the trade-off. Any decision worth mentioning cost you something — speed for correctness, coverage for time, elegance for a deadline. Juniors describe what they built. Seniors describe what they gave up to build it. Saying the cost out loud is a shortcut to being read as the second kind.

If you keep one thing: say what you chose against.' where slug = 'interview-craft';

update public.lessons l set theory_md = 'There is a belief, common among people who are good at their jobs, that an interview is where you prove depth by displaying it. It is not. Depth is proved by control — by being able to put the explanation at whatever altitude the room needs.

The room is almost always mixed. Someone who does your job. Someone who will manage you. Frequently someone from a different function entirely, there for the read on whether you can be worked with. If you pitch at the first of those, the other two spend ninety seconds waiting, and they are usually the ones who write *unclear communicator* in the notes.

Aim at the least technical person present. The specialist will not think less of you for it — they will think you can be put in front of a customer, which is the thing their team is usually short of.

The mechanics are simple and take practice.

**Say what it was for before you say what it was.** Purpose before mechanism. *We needed to stop double-charging people* lands before any description of the system that did it.

**One layer of jargon, defined in passing.** Not zero: zero sounds evasive. *It was a reconciliation job — basically a nightly check that the two sets of numbers agree.*

**Analogies only where they are honest.** A bad analogy costs more than the term it replaced, because now they have to unlearn it.

**The move:** say what it was for, then what it was, in language the least technical person in the room can follow.

The tell that you have got this right is that the non-specialist asks a question. That never happens when the answer was pitched over their head — they stay quiet, and quiet is not agreement.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-craft' and l.sort_order = 1;

update public.lessons l set theory_md = 'Two candidates describe the same project. The first says what they built. The second says what they built and what they gave up to build it. The second is read as more senior, and neither of them mentioned a job title.

The reason is that every decision worth talking about had an alternative, and the alternative had merit. Speed against correctness. Coverage against time. The elegant version against the version that shipped. A candidate who describes only the choice they made is describing a task. A candidate who names the road not taken is describing a judgement, and judgement is the thing being bought.

**The move:** for any decision you describe, name the alternative and why you did not take it.

There is a sentence pattern that does this in one breath: *We could have X, and the reason we did not was Y.* Three of those in an interview will change how you are heard.

The strongest version admits the cost was real. *We shipped without the audit log, which meant support spent about a month answering questions they should not have had to. I would do it again, because the alternative was missing the season.* That is a person weighing, not a person justifying.

Two cautions. Do not manufacture trade-offs where there were none — a decision presented as agonising when it was obvious sounds like padding. And do not describe a trade-off you now think you got wrong without saying so; the interviewer will spot it, and the credit for noticing goes to whoever says it first.

The same move works when the decision was not yours. *The call was made to go with the vendor. I argued for building it, and the reason I lost is that we had no one to maintain it, which was a fair point.* That shows you can disagree and then commit, which is rarer and more valuable than being right.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-craft' and l.sort_order = 2;

update public.lessons l set theory_md = 'The four-minute answer is almost never the result of having too much to say. It is the result of not knowing where to stop, which is a different problem and has a mechanical fix.

Answer at one level. Then offer the next one and stop.

*So that is the shape of it. I can go into how we actually did the cutover, if that is useful.* Then silence, and let them choose. Three things happen. They get an answer at the length they wanted. You demonstrate that there is more without spending it. And you hand them a conversational turn, which turns an interrogation into a conversation — that shift alone is worth more than the extra detail you were about to give.

**The move:** answer one layer deep, offer the next layer, then stop and let them ask.

The offer must be genuine, which means being ready for a yes. If you offer the mechanics of the cutover, have the mechanics. An offer you cannot honour is worse than no offer.

Watch for the two tells that you have poured rather than offered. If you have said *and then*, *and also* or *sorry, one more thing* you are pouring. And if the interviewer has started nodding rhythmically, you passed the exit some time ago.

There is a recovery move for when you notice you are three minutes in: stop mid-thought and land it. *I am going long — the short version is that we got it down to one release a week. Happy to go back into any part of that.* No apology beyond four words. Candidates who can land a runaway answer are rated better than those who never took off, because the recovery is itself a demonstration of self-awareness.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-craft' and l.sort_order = 3;

update public.lessons l set theory_md = 'The live problem — a whiteboard, a case, a scenario invented on the spot — is not testing whether you get the answer. It is testing what you are like to think alongside, because that is what working with you will feel like every day.

Which means silence is the only genuine failure. A wrong direction, narrated, is assessable. Ninety seconds of quiet staring is not, and the interviewer''s notes will say *hard to follow* regardless of what you were doing in there.

Four moves, in order.

**Say the problem back.** In your own words, briefly. It catches misunderstandings while they are free, and it buys you fifteen seconds of thinking time that looks like work.

**Ask the constraints.** How many users, how much time, what already exists, what does not matter. Every question you ask is a mark in your favour — a candidate who starts building without asking what they are building has told you something.

**Narrate the branch.** *There are two ways I could go here. The obvious one is X. The reason I am hesitating is Y.* Then pick one and say why.

**Say when you are stuck.** *I am stuck on this bit* is a completely respectable sentence, and it usually produces a hint, and taking a hint well is itself part of what is being tested.

**The move:** narrate the branch you are choosing between, and say out loud when you are stuck.

The one thing to avoid: pretending to think while actually panicking. It is visible. The fix is to go back to the second move and ask a constraint question — it is legitimate, it is useful, and it will settle you.

If you finish and the answer is wrong, saying so is worth more than the answer would have been. *I think I have got this the wrong way round, actually. Give me a second.*'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-craft' and l.sort_order = 4;

update public.lessons l set theory_md = 'Confidentiality, security clearance, an unreleased product, a client who would recognise themselves in one sentence. Sooner or later your best example is one you cannot tell.

Most people handle this badly in one of two directions. They either say *I cannot discuss that* and stop, which reads as unhelpful and wastes the strongest material they have. Or they tell it anyway, which tells the interviewer exactly what you will do with their secrets in two years.

The way through is to describe the shape and remove the identity.

**Abstract the domain.** *A regulated industry where a mistake gets reported to a regulator.* *A consumer product with a few million users.*

**Keep the structure, change the specifics.** The size of the team, the nature of the constraint, the decision you faced — all of that is yours to tell. The client''s name, the numbers, the mechanism, may not be.

**Say the boundary once, without ceremony.** *I will keep this vague on the client and specific on what I did.* One sentence, said lightly, and then get on with it.

**The move:** name the boundary once, then describe the shape of the work in full.

Done well, this is a net positive. The interviewer learns what you did and simultaneously watches you handle confidential information with care in real time. That is a live demonstration of trustworthiness, which no answer about your integrity could ever provide.

Two failure modes. Over-signalling — repeating *I cannot say much about this* five times, which is tedious and makes you sound like you have nothing. And the false boundary: claiming confidentiality to avoid a question you simply do not want to answer. Interviewers can usually tell, because a real boundary is specific and a fake one is convenient.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-craft' and l.sort_order = 5;

update public.skills set takeaway_md = 'The screening call is not a formality, and treating it as one is why good candidates lose before anyone technical has met them.

The person on the phone is usually deciding three things: can you hold a conversation, do you want this specific job, and is there anything alarming. They are not qualified to assess your craft and they know it. Answers pitched at a specialist land as evasive, because they cannot tell whether you answered.

Register matters more here than anywhere else in the process, because there is no face to read. If they are brisk, be brisk. If they are chatty, spend the extra thirty seconds. Mirror the length of their sentences and you will be read as easy to work with, which is the entire brief for this call.

Two specifics. Have a one-line answer to *why this company* that could not be said about any other company — it is the question most people fail, and the bar is low. And when you have finished an answer on the phone, stop, even though the silence is longer down a line. The pause you fill is the pause they were using to type.

If you keep one thing: answer the question they asked, at the length they asked it.' where slug = 'interview-rapport';

update public.lessons l set theory_md = 'More good candidates are lost on the twenty-minute screening call than at any other stage, and almost all of them are lost for the same reason: they treated it as an administrative step.

Understand what the person on the phone is actually doing. They are usually not able to judge your craft, they know it, and they are not trying to. They are deciding three things.

**Can this person hold a conversation.** They will be putting you in front of a hiring manager whose time is expensive, and the recruiter''s own credibility is spent on that introduction.

**Do they want this specific job.** Not a job. This one. A candidate who cannot say why is a candidate who will drop out at offer stage, which is the recruiter''s worst outcome.

**Is there anything alarming.** Bitterness about a previous employer, evasiveness about dates, a salary expectation twice the band, availability that does not work.

Nothing on that list is about how good you are. So an answer built to demonstrate expertise is aimed at a target that is not there — and worse, it usually arrives as evasive, because the listener cannot tell whether you answered.

**The move:** answer the three questions they are actually asking — can you talk, do you want this, is anything wrong.

Two practical consequences. Have a one-line answer to *why us* that could not be said about anyone else. And treat the recruiter as a person who will be an ally for the rest of the process, because they usually become one: they brief the panel, they tell you what the manager cares about, and they argue for you in the debrief. Candidates who are brisk with recruiters lose an advocate they never knew they had.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-rapport' and l.sort_order = 1;

update public.lessons l set theory_md = 'Rapport on a call is not warmth. It is fit — the sense that talking to you costs the other person nothing. And on a phone call, with no face to read, fit is carried almost entirely by two things: how long your sentences are, and how formal they are.

People are extremely sensitive to mismatch here and almost never conscious of it. A brisk caller who gets ninety-second answers experiences you as heavy going. A chatty caller who gets clipped answers experiences you as cold, and will describe you that way afterwards without being able to say why.

So read the first thirty seconds and match.

**Length.** If their questions are one sentence, answer in three or four, not fifteen. If they are telling you about their weekend, you have room.

**Formality.** Borrow their vocabulary. If they say *the guys on the team*, you can too. If they say *the delivery function*, stay in that register.

**Pace.** Fast talkers experience pauses as hesitation; slow talkers experience speed as pressure.

**The move:** match the length and formality of their sentences, in the first two exchanges.

This is not chameleon behaviour and it is not insincerity. It is the same adjustment you make between talking to a colleague and talking to your grandmother, done deliberately for twenty minutes.

One asymmetry worth knowing: it is easier to loosen than to tighten. Start slightly more formal than you expect to end, and follow them down. Starting too casual with someone who turns out to be formal is a hole that takes the whole call to climb out of.

And when they laugh, laugh. Candidates so braced for assessment that they miss a joke are read as tense, and tense is the adjective that ends a screening call.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-rapport' and l.sort_order = 2;

update public.lessons l set theory_md = 'This is the question most candidates fail, and the bar is embarrassingly low. Most answers are a compliment, a description of the company back to itself, or a statement about the candidate''s own career. None of those answer it.

A real answer has one property: it could not be said about the company across the road.

Getting there takes about fifteen minutes of preparation, and the fifteen minutes are not spent on the About page.

**Look at what they have shipped or changed recently.** A product decision, a blog post, a restructure, a pricing change.

**Look at the job description as evidence.** How a role is written tells you what has been going wrong. A description that mentions stakeholder management four times is a description of a job where nobody could get anything agreed.

**Find one person.** Someone who works there, has written or spoken about it, and said something that told you what it is like inside.

Then build the line: one specific thing, plus what it tells you, plus why that matters to you.

**The move:** name one specific thing about them, say what it tells you, say why that is what you want.

Length is a trap here. Over about thirty seconds it stops sounding like a reason and starts sounding like a pitch. Say it, then stop.

Two warnings. Do not use the product-love answer unless it is true and specific — *I use it every day* invites *what would you change?* and there is no recovering from having nothing. And avoid praise entirely: telling a company it is a market leader is information they already have, delivered by someone with no standing to grade them.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-rapport' and l.sort_order = 3;

update public.lessons l set theory_md = 'The interview starts before the first question, and a surprising amount of the verdict is set in the part everyone treats as preamble.

This is not because interviewers are shallow. It is because the opening exchange is the only unstructured data they get — everything after it is rehearsed, and they know it. So the two minutes about your journey, the weather, the building, is the sample of you they trust most.

Three things to get right.

**Have something to say when they ask how you are.** Not *fine*. A specific, light, true sentence. *Good — mildly astonished to find your building on the first attempt.* It costs nothing and it is the first evidence they have that talking to you is easy.

**Bring one question of your own into the opening.** Not a prepared one. Something about the room, the office, the day. It turns two people performing roles into two people talking.

**Land the transition deliberately.** When they say *so, shall we get started* — sit up slightly, close the small talk cleanly. Candidates who keep chatting past the transition are read as not picking up signals.

**The move:** answer the greeting with something specific and true, then follow their transition into the interview cleanly.

On video, three additional things, all mechanical and all worth more than they should be. Be there two minutes early and already unmuted. Look at the camera for the first sentence and the last one, whatever you do in between. And have a plan for the technology failing, said out loud without embarrassment — *shall I dial in instead?* — because it will happen to someone today and being the person who handles it calmly is free credit.

Do not over-invest. The opening is not where the job is won. It is where it is quietly made easier or quietly made harder.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-rapport' and l.sort_order = 4;

update public.lessons l set theory_md = 'A phone interview removes about half the information both people are using, and almost every problem specific to phone screens comes from one of two things: silence that is misread, or turn-taking that goes wrong.

**Silence gets longer.** In person, a two-second pause is filled by a face — a nod, a thinking expression. On a call it is two seconds of nothing, and nothing is uncomfortable, so both people start talking to end it. The candidate over-explains; the interviewer interrupts. Neither meant to.

The fix is to be slightly more explicit than feels natural. Signal the end of an answer out loud: *…and that is where it landed.* Signal thinking out loud: *Let me think about that for a second.* Both are unnecessary in person and load-bearing on a call.

**Turn-taking has no visual cue.** The tiny lean forward that says *I want to speak* is invisible. So when you collide with them, stop immediately and hand it over — *no, go on* — and do it fast. Two people apologising simultaneously for ten seconds is the most common phone-interview embarrassment there is.

**The move:** say out loud when you have finished an answer, and when you are thinking.

Two more, both cheap. Backchannel — the small *mm*, *right*, *got it* while they are talking. In person you nod; on the phone, nodding is silence, and silence reads as absence. And stand up. It changes the voice more than anyone expects, and voice is the entire channel.

Finally: nothing about your setting is invisible. A call taken while walking, in a car, or in a room with an echo is read as a call you did not prioritise, and that judgement is made in the first ten seconds.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-rapport' and l.sort_order = 5;

update public.skills set description = '*Any questions for us?* — the ten minutes most candidates waste being polite.' where slug = 'interview-your-questions';

update public.skills set takeaway_md = 'This is the only part of the hour you control, and most people hand it back.

The test for a good question is simple: could this person answer it, and could the website not? *What does success look like in this role in six months* passes. *What is the culture like* fails, because they will say collaborative and you will both know nothing happened.

Aim your questions at the work itself, in the present tense, as though you already had the job. What is the thing the team keeps having to redo. What would you want the person in this seat to have fixed by Christmas. Asking those makes the interviewer picture you in the seat, and that picture is worth more than any answer you gave earlier.

Ask about the person too, once. People remember conversations, not interrogations, and *what made you stay* is the question that most reliably turns an interview back into a conversation.

Keep one in reserve for the end, and do not ask about money here — that is its own skill and its own moment.

If you keep one thing: the questions you ask are an answer.' where slug = 'interview-your-questions';

update public.lessons l set theory_md = '*Any questions for us?* is the only part of the hour where you choose the subject, and most candidates hand it straight back.

The test for a question worth asking is a single line: could this person answer it, and could the website not.

That rules out most of what gets asked. Culture — the website says collaborative. Growth plans — the press release said what the press release says. Training budget — a policy, and asking about it in a first interview signals you are thinking about leaving before you have arrived.

It rules in anything that requires this person''s own experience. What they find hard. What they were wrong about. What changed after the last reorganisation. What the person before you did well.

**The move:** ask something this specific person knows and no document contains.

There is a second, quieter function to this. The questions you ask are the last thing said in the room, and they are read as evidence of what you pay attention to. A candidate who asks about the on-call rota, how decisions get unstuck, and what happened to the previous postholder has demonstrated three things about how they think about work — without making a single claim about themselves.

Prepare five and expect to use three. Two will get answered during the interview, and saying so is good — *I had one about how the roadmap gets set, but you covered it* shows you were listening and had prepared, in nine words.

One thing to avoid: the question designed to display your knowledge. Everyone can hear it, it is not a question, and the interviewer has to sit through it politely.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-questions' and l.sort_order = 1;

update public.lessons l set theory_md = 'There is a class of question that does something beyond gathering information: it puts you in the job in the interviewer''s mind, for the length of the answer.

They are questions asked in the present tense, about the work, as though the decision had already been made.

*What would you want the person in this seat to have fixed by Christmas?*
*If I started on Monday, what is the first thing that would land on me?*
*Who would I be arguing with most in the first month?*

The interviewer has to imagine you there in order to answer. That imagining is worth more than anything you said about yourself in the previous forty minutes, because it is theirs rather than yours — people believe the pictures they construct.

**The move:** ask about the work in the present tense, as though you already had the job.

Two calibrations.

**Do not overdo it.** One or two of these. A candidate who asks five presumptuous questions is a candidate who has decided the outcome, and interviewers notice.

**Keep them answerable.** *What would my first ninety days look like* is often too vague to produce a real answer — most managers have not thought about it in that form. *What is the first thing that would land on me* is concrete and gets a specific answer.

The best version of this question type asks about difficulty rather than opportunity. *What is the part of this job that people underestimate?* invites honesty, gets an answer worth having, and quietly tells them you are the sort of person who asks what is hard before asking what is nice.

If the answer sounds alarming, that is information you were going to receive on day thirty anyway, at a much higher price.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-questions' and l.sort_order = 2;

update public.lessons l set theory_md = 'Interviews are asymmetric by design, and for fifty minutes the interviewer is a function rather than a person. One question that treats them as a person is worth more than three about the role.

*What made you stay?*

That is the whole technique. Variations: what made you join, what nearly made you leave, what you would tell a friend applying. All of them do the same thing — they ask for an opinion rather than information, and opinions are the only thing anyone actually enjoys being asked for.

Two effects follow, and both matter.

**The register changes.** They stop reporting and start talking. Almost everyone gives a more honest answer to this than to anything else in the hour, and you learn more about the place from thirty seconds of it than from the entire careers site.

**They enjoy the interview.** That sounds soft and it is not. Interviewers write notes shortly afterwards, and the notes are written by a person with a feeling about how the conversation went. Being the candidate a tired interviewer enjoyed talking to is a real advantage, and it is available to anyone.

**The move:** ask one question that asks for their opinion rather than for information.

Two rules keep it honest. Once, not twice — a second personal question starts to feel like a technique, which it is, and the whole value is that it did not feel like one. And listen to the answer properly, including the pause before it; the hesitation before someone says why they stayed is frequently more informative than the sentence that follows.

If the answer is thin or evasive, that is data. Someone who cannot say why they have stayed four years has told you something worth knowing.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-questions' and l.sort_order = 3;

update public.lessons l set theory_md = 'Every open role exists because something is not working. Someone left, something grew, something broke, or something was promised that nobody can currently deliver. The job you are interviewing for is a response to a problem, and nobody will tell you what it is unless you ask.

There is a family of questions that get at it.

*What made this role necessary?*
*What was the previous person best at, and what did they find hardest?*
*If nobody is hired for this, what does not happen?*
*How long has the role been open?*

That last one is the cheapest and most revealing. Two weeks means growth. Seven months means either the bar is high or something in the description is wrong, and the answer to which will tell you a great deal about what you would be walking into.

**The move:** ask what problem this role exists to solve, and listen for what they leave out.

Two payoffs. The obvious one is that you learn what you are being hired to fix, which lets you aim the rest of your answers at it — and if the answer comes early enough, you can reframe your best story around it.

The subtler one is that asking this question is itself a signal. Candidates who want to know what is broken are read as people who fix things. Candidates who ask only about the good parts are read as people who want a nice job.

Ask it neutrally. There is a version of this that sounds like an audit, and it puts the interviewer on the defensive. The tone you want is genuinely curious, and the phrasing that carries it best is usually the shortest: *what made the role necessary?*

Then listen for the pause. This is a question people answer carefully, and the care is the information.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-questions' and l.sort_order = 4;

update public.lessons l set theory_md = 'Asking the same three questions of everyone you meet in a process wastes most of them, and in a panel day it is noticed — people compare notes, and *he asked all of us the same thing* is a real note.

Match the question to what the person can actually tell you.

**The recruiter** knows the process, the competing candidates, the timeline, and what the manager says when the door is closed. Ask about the process and the manager. Do not ask them about the work.

**The hiring manager** knows the job, the problem, the team''s weaknesses and what they need from this hire. Ask about the work, the difficulty, the first ninety days.

**The peer** knows what it is actually like — the meetings, the frustration, whether the tools are any good, whether people stay late. Ask what a bad week looks like. This is the most honest room you will be in and most candidates waste it on questions about strategy.

**The skip-level or executive** knows where the whole thing is going and what would make it fail. Ask about direction, about what would have to be true in two years, about the constraint they worry about.

**The move:** ask each person about the part of the job only they can see.

Two practicalities. Keep one question in reserve for the very end of the last conversation, because processes overrun and the question slot is what gets cut. And write down the answers between conversations — you will be told contradictory things, and the contradictions are the most valuable data in the whole day. A team that disagrees about what the role is for is telling you something no answer could.

If you are running short of questions by the fourth interview, ask the same question about a different thing: what is the hardest part of *your* week, rather than the hardest part of the role.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-your-questions' and l.sort_order = 5;

update public.skills set description = 'Expectations, ranges, and the conversation after *we would like to make you an offer*.' where slug = 'interview-money';

update public.skills set takeaway_md = 'The number is decided by whoever is calmer, and calm here is almost entirely preparation.

Know two figures before you speak to anyone: what the market pays for this work in this place, and the number below which you would say no. The second one is private and never spoken aloud, and it is what stops you negotiating against yourself at nine in the evening.

When asked early for expectations, you have three honest moves: give a researched range, deflect once to learn the band they have budgeted, or ask what the range is. Deflecting twice starts to read as gamesmanship. If you give a range, give it with a reason — the reason is what turns a number into a position rather than a hope.

After an offer, the whole game is asking rather than arguing. *Is there flexibility on the base* is a question, and questions do not put anyone on the defensive. Then say nothing, because the silence after that question is where the flexibility appears.

Say thank you, ask for it in writing, and take a night on it. Nothing you gain by answering immediately is worth what you lose by not thinking.

If you keep one thing: never negotiate against a number nobody has said yet.' where slug = 'interview-money';

update public.lessons l set theory_md = '*What are your salary expectations?* arrives early, often in the first call, and the instinct is either to name a low number to stay safe or to refuse to answer at all. There are three honest moves and each is right in different circumstances.

**Give a researched range, with the reason.** *I have been looking at the mid-sixties to mid-seventies for this level of role in this city, based on what I have seen advertised and two conversations with recruiters.* The reason is what turns a number into a position. A number alone can be argued down; a number with evidence behind it has to be argued with.

**Ask what the band is.** *Do you have a band for the role?* Perfectly normal, frequently answered, and it costs nothing. Many employers publish bands internally and will simply tell you.

**Deflect, once.** *I would rather understand the role properly first — can we come back to it?* This works exactly one time. A second deflection reads as gamesmanship and starts to irritate.

**The move:** name a researched range with its reason, or ask for theirs — and never deflect twice.

The advice that whoever speaks first loses is mostly wrong for candidates. It is true in a negotiation between equals with symmetric information. In hiring, the employer knows the band and you do not, so refusing to engage usually just delays a conversation you will have anyway, with less goodwill.

Two specifics. If you give a range, be prepared to be offered its bottom — so the bottom of your stated range should be a number you would genuinely accept. And never give a range whose top you cannot justify; the question *why that figure?* will come, and having an answer is most of the battle.

If they will not say the band and press you for a number, give the range. The information asymmetry is not going to resolve itself, and being difficult about it costs more than it wins.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-money' and l.sort_order = 2;

update public.lessons l set theory_md = 'The moment an offer is made is the only moment in the entire process when your leverage is real, and it lasts about a day.

Everything before it was you competing. Now they have chosen, they have told other candidates no, and the person who made the offer would very much like to stop recruiting. That is not a weapon and it does not need to be. It simply means a reasonable request is likely to be met, and that asking is normal.

The whole technique is one sentence and one silence.

*Thank you — I am pleased. Is there any flexibility on the base?*

Then stop talking.

It is a question, not a demand, so nobody has to defend anything. And the silence afterwards is where the answer comes from. Almost every candidate who loses money here loses it by filling that pause — by explaining, by justifying, by pre-emptively saying it is fine if not.

**The move:** ask whether there is flexibility, then say nothing until they answer.

Three supporting habits.

**Say thank you first and mean it.** Enthusiasm and negotiation are not opposites, and the version of this that goes badly is the one that sounds like disappointment.

**Ask for it in writing, and take a night.** Nothing you gain by accepting on the phone is worth what you lose by not thinking. *Can you send that over? I would like to read it properly and come back to you tomorrow* is completely standard and nobody has ever withdrawn an offer over it.

**One ask, not three rounds.** Ask, hear the answer, decide. A negotiation that goes back and forth four times spends goodwill you will need on your first day.

If the answer is no, that is fine. You have lost nothing — the offer does not evaporate because you asked, and an employer who would withdraw it for that has told you something useful very cheaply.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-money' and l.sort_order = 3;

update public.lessons l set theory_md = 'Base pay is the number everyone negotiates and often the one with least room in it, because it sits inside a band that somebody else approved. The rest of the package is frequently more flexible and almost nobody asks.

What is usually available.

**Start date.** The cheapest thing to move and worth real money if you have holiday to take or a gap you wanted.

**Holiday.** Sometimes fixed by policy, sometimes not, and often possible as unpaid additional leave even where the paid allowance is rigid.

**A signing amount.** Common where the band is genuinely inflexible, because it comes from a different budget and does not set a precedent for anyone else''s salary.

**Working pattern.** Days in the office, hours, a compressed week. This is the request that has changed most in recent years and it is frequently granted.

**Review timing.** A salary review at six months rather than twelve, written down. This is the quiet one: it costs the employer nothing today, so it is often agreed, and it changes what happens next year.

**Title.** Free, and it affects your next job more than this one.

**The move:** if the base will not move, ask what else can.

Say it in exactly those terms. *I understand the base is fixed. Is there flexibility anywhere else?* It is a cooperative question — you have accepted their constraint and invited them to solve the problem with you, and people respond well to being asked for help.

Two cautions. Ask for one or two things, not a list; a list turns a conversation into a negotiation and changes the temperature. And get anything agreed written into the offer letter, kindly and without suspicion — *would you mind putting the review date in the letter, just so it does not get lost when you and I both forget about it in November?* Verbal agreements outlive the manager who made them approximately never.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-money' and l.sort_order = 4;

update public.lessons l set theory_md = 'How a process ends is remembered longer than how it went, because the ending is the part where people find out what you are like when you have nothing to gain.

**Saying yes.** Do it clearly and warmly, in writing, and stop negotiating. A candidate who accepts and then reopens something has spent their first political capital before day one. Then tell everyone who helped — the recruiter especially, who has been quietly arguing for you in rooms you were not in.

**Saying no.** Promptly, warmly, and without a fabricated reason. *I have accepted something else* is a complete sentence and it requires no elaboration. Do not invent a problem with their offer to make the refusal feel justified — it invites them to fix it, and now you are having a conversation you did not want. The industry is small, hiring managers move, and the person you decline this year interviews you in four years'' time surprisingly often.

**The competing offer.** If you genuinely have one, saying so is legitimate and it should be stated as a fact with a deadline, not as a threat. *I have another offer and I need to answer by Thursday. You are my first choice, and I wanted to tell you rather than let the clock run out.* That is honest, it is useful to them, and it gives them a reason to move quickly.

**The move:** end it in the way you would want to be told — promptly, warmly, and without invention.

Never bluff a competing offer you do not have. The failure mode is not that you are caught. It is that they say *we understand, good luck*, and there is nowhere to go.

And if you are turning down an offer you nearly took, say what you liked about them. It costs a sentence, it is usually true, and it is the thing that gets remembered when your name comes up again.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-money' and l.sort_order = 5;

update public.lessons l set theory_md = 'Interviewers are not mind readers, and enthusiasm is not the same as intent. A candidate can be warm, engaged and interesting for fifty minutes and still leave the room without anyone knowing whether they would take the job.

Say it. Out loud, as a sentence, near the end.

*I should say plainly — I want this job.*

That is it. It is not a technique, it is a piece of information, and it is startling how few people supply it. Interviewers debrief afterwards and one of the first things said in that room is some version of *were they into it?* A candidate about whom nobody can answer that is a candidate who is easy to leave behind in favour of someone who was obviously keen.

**The move:** state, in one plain sentence, that you want the job.

Three things make it land.

**Plainness.** Not *I would be excited by the opportunity*, which is a construction people use when they are being polite. Short declarative sentences read as true.

**A reason attached.** *I want this job, and the reason is the thing you said about the reporting mess — that is exactly the work I like.* The reason is what stops it sounding like something you say at the end of every interview.

**Timing.** Near the end, after you have heard enough to mean it. Said in the first ten minutes it is a pitch; said at the end it is a conclusion.

The fear is that declaring interest weakens your position on money later. It does not. Salary is decided by the band and by whether they want you, and being obviously willing makes them want you more, not less. Playing hard to get in a hiring process mostly results in not getting.

If you do not want the job, do not say it. Say something true instead, or say nothing.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-closing' and l.sort_order = 1;

update public.lessons l set theory_md = 'There is one question that can change the outcome of an interview after it is over, and almost nobody asks it.

*Is there anything about my background that gives you pause?*

Here is why it matters. The moment you leave, a conversation happens in which someone raises a doubt about you — too junior, no experience of that sector, a gap on the CV, an answer that was thin. You are not in that room. Nobody argues the other side. The doubt goes unanswered, and unanswered doubts decide close calls.

Asking this question is the only chance you get to answer an objection before it is discussed without you.

**The move:** ask what would give them pause, then answer it briefly and without defending.

It is uncomfortable to ask, and the discomfort is the price. Three things make it work.

**Ask it as a genuine question.** Curious, not anxious. *Is there anything you are unsure about that I could address?*

**Then be quiet.** The answer often takes a few seconds to arrive, because you have asked for candour and most interviewers have to decide how honest to be.

**Answer briefly.** One or two sentences. A long rebuttal turns a small doubt into a big subject, and the interviewer will remember the length rather than the content.

If the answer is *no, nothing*, you have lost nothing and gained a small demonstration of confidence. If the answer is real, you have just been handed the single most useful piece of information in the entire process — and even if you cannot fix it, you know what to put in the follow-up note.

Do not do this in a first screening call with a recruiter who cannot answer it. Save it for the person who will be in the debrief.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-closing' and l.sort_order = 2;

update public.lessons l set theory_md = 'The thank-you note is nearly universal advice and nearly universally wasted, because almost every one of them says the same thing: thank you for your time, I enjoyed our conversation, I remain very interested.

That note is fine. It is also identical to the one from every other candidate, which means it carries no information and changes nothing.

A note that works does one job: it adds something that was not in the room.

**A better version of an answer you fumbled.** *You asked how I would approach the reporting problem and I gave you a vague answer. Having thought about it on the train, the first thing I would actually do is…* Two sentences. This is the strongest kind, because it demonstrates that you keep thinking about problems after you leave.

**Something useful about the thing they described.** A link, a tool, a name of someone who solved it elsewhere. It costs you ten minutes and it makes you the candidate who was already helping.

**An answer to the objection they named.** If you asked what gave them pause and they told you, this is where you address it properly.

**The move:** send one short note that adds something the interview did not contain.

Rules of length and timing. Short — under a hundred and fifty words. Same day or the next morning, not four days later. To the person you spoke to, and to the recruiter separately if there was one.

And once. A second unprompted note undoes the first entirely: the first says you are thoughtful, and the second says you are anxious. If you have not heard by the date they gave you, that is a different thing, and it is the subject of the next lesson.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-closing' and l.sort_order = 3;

update public.lessons l set theory_md = 'Waiting is the part of a process you control least and behave worst in. Almost every candidate error here comes from filling a silence that means nothing.

Hiring is slow for reasons that have nothing to do with you. Someone is on holiday. The panel cannot get a slot. There is another candidate at a different stage and they want to see both before deciding. A budget approval has stalled two levels up. None of that is a signal, and reading it as one produces the message you should not send.

Two rules make this simple.

**Get a date before you leave.** *When would you expect to be in touch?* Ask it in every interview. It converts an open-ended wait into a deadline, and a deadline gives you permission to chase without inventing a reason.

**Chase after the date, not before.** One message, short, warm, no reproach: *You mentioned you would know by the end of last week — no rush at all, just wanted to check where things stand.* Then wait the same interval again before a second, and after that stop.

**The move:** ask when they expect to decide, then chase once, after that date has passed.

Chase through the recruiter if there is one. It is their job, they do not mind, and it saves the hiring manager an interaction that costs you a small amount of goodwill.

The tone that works is unbothered. Not casual — unbothered. You have other things going on and this is a reasonable enquiry rather than a plea. If you are struggling to write it that way, the fix is usually to make it shorter; anxiety lives in the second and third sentences.

And keep interviewing elsewhere while you wait. It is practical advice and it is also the fastest route to the tone described above.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-closing' and l.sort_order = 4;

update public.lessons l set theory_md = 'A rejection is the end of one process and the start of a much longer relationship that most candidates burn down in a single reply.

Hiring managers move companies. Recruiters remember two kinds of candidate: the ones who were rude when rejected, and the ones who were not. Second-choice candidates get called back with surprising frequency, when the first choice declines or leaves inside a year. None of that is a reason to be gracious — being gracious is its own reward — but it is a reason not to treat a no as the end of anything.

One reply, three sentences.

**Thank them properly.** Briefly and without sarcasm, which is harder than it sounds on the day.

**Ask for one specific thing.** Not *any feedback would be appreciated*, which is easy to ignore. *Was there a particular gap that decided it?* is answerable in one line, so it often gets answered.

**Leave the door open, plainly.** *If something similar comes up, I would be glad to hear from you.*

**The move:** thank them, ask one specific question, and say you would come back.

On the feedback itself: take it, do not argue with it, and understand that a lot of it will be soft or partly untrue. Companies are cautious about rejection reasons for legal and human reasons alike. If you get one useful sentence out of three attempts, that is a good rate. Ask, thank, and move.

And give yourself the day. The reply does not have to be sent in the first hour, and the version written in the first hour is rarely the one you want on record. Write it, leave it, send it in the morning.

If you got to the final stage and lost, ask what the successful candidate had that you did not. It is a harder question to ask and it produces the most useful answer available.'
  from public.skills s
  where l.skill_id = s.id and s.slug = 'interview-closing' and l.sort_order = 5;
